### PR TITLE
Improvement on  code structure, performance

### PR DESCRIPTION
**Pull request by pcgayan**

### CODE REVIEW

**Comment by pcgayan** [comment]
there are more improvements i can do, let me know if you guys approve these so I can move forward.

**Comment by ghost** [comment]
I'm not really looking for non-functional contributions. In what way do you think your changes improve structure and performance? There are no known performance issues with this application. If you've addressed one or more significant issues, I'll consider merging but I need more information on what you think you've achieved here.

Thank you

**Comment by pcgayan** [comment]
HI Martin,
I am senior java + android developer. I started using micro bit android
code base. if you do a diff on the merge you can see the improvements as
follows,

# unused imports
# global variable which can be made local
# global variable declarations which not used.
# possible memory leaks > some handlers are not set to static
# some code duplicates which easy our life if we make them declared once
and refered in other places with out duplicating.

I understand the application does not have performance issue for average
devices, but my PR may show possible ways to improve the application by
certain coding enhancements. Just wanted to make the code more beautify for
the community. :)

Regards,
Gayan.

**Comment by ghost** [comment]
Thanks for summarising. I'm very short of time, so that's a big help. 

What testing have you done?

**Comment by pcgayan** [comment]
yes, i have tested these the apps, works like a charm.

**Comment by pcgayan** [comment]
Hi Team,
Thank you very much for prompt replies.

I agree these changes will not add “new functionality or no solve problems”

As I have summarized there are :
1 possible memory leaks > some handlers are not set to static
2 some code duplicates which easy our life if we make them declared once and referred in other places without duplicating.

As I am core java + android developer (https://www.linkedin.com/in/gayan-priyanatha-529a0336/)
I appreciate if these changes are picked up, if you undergo the changes I have done you don’t have to test the app even. (Since they are 100% logical changes)
There are bunch of more enhancements + code duplicates which I can fix, let me now if guys agree on this so I can do the rest.

**Comment by ghost** [comment]
I disagree with your statement that I don't have to test your changes. How many developers have I heard say "It works, you don't need to test it"?

Again, you'll have to be patient. I'll look at this properly when I have time.

**Comment by pcgayan** [comment]
Oki :), Ill be patient. I have tested the app as far as i know.
take your time.

**Comment by ghost** [comment]
That's better :-)

For enhancements, could you document each proposed enhancement as a separate Git Issue please? Then I can appraise the idea and let you know what I think before you put work into coding.

**Comment by pcgayan** [comment]
Sure, ill create issues with docs for separate ideas.

**Comment by ghost** [comment]
There are too many completely cosmetic code formatting changes in this PR. I'm not willing to merge this code.

Please see the updated README for the policy on contributing. If you think there are issues, please document them in the issue tracker. I will not be accepting PRs without prior discussion./

Thank you

**Pull request closed without merging**
